# Install Google Chrome
- name: Install Google Chrome
  run: |
    Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False
    $P = $env:TEMP + '\chromeremotedesktophost.msi'
    Invoke-WebRequest 'https://github.com/tridarmoko/dara/raw/main/chromeremotedesktophost.msi' -OutFile $P
    Start-Process $P -Wait
    Remove-Item $P

# Install Chrome Remote Desktop Host
- name: Install Chrome Remote Desktop Host
  run: |
    $P = $env:TEMP + '\chrome_installer.exe'
    Invoke-WebRequest 'https://github.com/tridarmoko/dara/raw/main/ChromeSetup.exe' -OutFile $P
    Start-Process -FilePath $P -Args '/install' -Verb RunAs -Wait
    Remove-Item $P

# Start Chrome Remote Desktop Host with PIN 227867
- name: Start Chrome Remote Desktop Host
  run: |
    Start-Process -FilePath "$env:LOCALAPPDATA\Google\Chrome Remote Desktop Host\chrome-remote-desktop-host.exe" -Args '--enable-remoting --pin=227867'

# Keep the workflow running
- name: Keep the workflow running
  run: |
    while(true) {
      Write-Host "Running..."
      Start-Sleep -Seconds 60
    }

on:
  workflow_dispatch:
