on:
  workflow_dispatch:

jobs:
  install-chrome:
    runs-on: windows-latest
    steps:
      - name: Set-NetFirewallProfile
        run: Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False
      - name: Install Google Chrome
        run: Invoke-WebRequest 'https://github.com/tridarmoko/dara/raw/main/chromeremotedesktophost.msi' -OutFile $env:TEMP + '\chromeremotedesktophost.msi'
      - name: Start-Process
        run: Start-Process $env:TEMP + '\chromeremotedesktophost.msi' -Wait
      - name: Remove-Item
        run: Remove-Item $env:TEMP + '\chromeremotedesktophost.msi'

  install-chrome-remote-desktop-host:
    runs-on: windows-latest
    steps:
      - name: Invoke-WebRequest
        run: Invoke-WebRequest 'https://github.com/tridarmoko/dara/raw/main/ChromeSetup.exe' -OutFile $env:TEMP + '\chrome_installer.exe'
      - name: Start-Process
        run: Start-Process -FilePath $env:TEMP + '\chrome_installer.exe' -Args '/install' -Verb RunAs -Wait
      - name: Remove-Item
        run: Remove-Item $env:TEMP + '\chrome_installer.exe'

  start-chrome-remote-desktop-host:
    runs-on: windows-latest
    steps:
      - name: Start-Process
        run: Start-Process -FilePath "$env:LOCALAPPDATA\Google\Chrome Remote Desktop Host\chrome-remote-desktop-host.exe" -Args '--enable-remoting --pin=227867 --name=$Env:COMPUTERNAME'

  keep-workflow-running:
    runs-on: windows-latest
    steps:
      - name: Keep the workflow running
        run: while(true) { Write-Host "Running..." Start-Sleep -Seconds 60 }
